### ISSUE TITLE
Invalid json from uploadcare

### ISSUE THREAD

**Issue by tsvetann** [RexMorgan/uploadcare-node#21]
I get an error invalid json from uploadcare.

https://github.com/RexMorgan/uploadcare-node/blob/master/lib/main.js#L39  

This line is hiding the actual error. Can we change it so we see what's wrong?

**Comment by tsvetann** [comment]
just to clarify i get this error when i add the options {store: true}

**Comment by RexMorgan** [comment]
Yes, that line is swallowing the error and hiding it from you.

You can change it in your local version to see what the error is. Just edit the file in your `node_modules/uploadcare`, that should help you see what's happening.
